version: "3.3"


services:

  ofelia:
    image: mcuadros/ofelia:${TAG}

    command: daemon --docker

    labels:
      com.centurylinklabs.watchtower.enable: "true"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
