version: '3.3'


services:

  traefik:
    image: traefik:2.9

    command:
      # - "--api.insecure=true"
      # - "--log.level=DEBUG"


      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"

      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/.letsencrypt/acme.json"
    
    labels:
      - 'com.centurylinklabs.watchtower.scope=${PROJECT_NAME}'
      - 'com.centurylinklabs.watchtower.enable=true'
    
    environment:
      TZ: ${TZ}

    volumes:
      - ./volumes/.letsencrypt:/.letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

    networks:
      - traefik_network

    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080"

    restart: unless-stopped


networks:
  traefik_network:
    name: traefik_network
