version: '3.3'


services:

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    
    command:
      - '--label-enable'
      - '--cleanup'
      - '--interval ${POLL_INTERVAL}'

    labels:
      - 'com.centurylinklabs.watchtower.enable=true'

    environment:
      TZ: ${TZ}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    network_mode: none
