version: "3.8"

services:


  cache:
    image: redis:${REDIS_TAG}
    restart: unless-stopped

    labels:
      - 'com.centurylinklabs.watchtower.enable=true'


  database:
    image: postgres:${DB_TAG}
    restart: unless-stopped

    labels:
      - 'com.centurylinklabs.watchtower.enable=true'

    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data

    volumes:
      - ${DB_VOLUME}:/var/lib/postgresql/data


  server:
    image: altran1502/immich-server:${TAG}
    entrypoint: ["/bin/sh", "./start-server.sh"]
    restart: unless-stopped

    labels:
      - 'com.centurylinklabs.watchtower.enable=true'

    env_file:
      - .env
    environment:
      - NODE_ENV=production

    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload

    depends_on:
      - cache
      - database


  microservices:
    image: altran1502/immich-server:${TAG}
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    restart: unless-stopped

    labels:
      - 'com.centurylinklabs.watchtower.enable=true'

    env_file:
      - .env
    environment:
      - NODE_ENV=production

    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload

    depends_on:
      - cache
      - database


  machine-learning:
    image: altran1502/immich-machine-learning:${TAG}
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    restart: unless-stopped

    labels:
      - 'com.centurylinklabs.watchtower.enable=true'

    env_file:
      - .env
    environment:
      - NODE_ENV=production

    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload

    depends_on:
      - database


  web:
    image: altran1502/immich-web:${TAG}
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    restart: unless-stopped

    labels:
      - 'com.centurylinklabs.watchtower.enable=true'

    env_file:
      - .env
    environment:
      - PUBLIC_IMMICH_SERVER_URL=${IMMICH_SERVER_URL}

    depends_on:
      - database


  proxy:
    image: altran1502/immich-proxy:${TAG}
    restart: unless-stopped

    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"

      - "traefik.http.services.immich.loadbalancer.server.port=8080"

      - "traefik.http.routers.immich-https.entrypoints=https"
      - "traefik.http.routers.immich-https.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.immich-https.tls.certresolver=letsencrypt"

      - "traefik.http.middlewares.immich-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.immich-https.redirectscheme.permanent=true"

      - "traefik.http.routers.immich-http.entrypoints=http"
      - "traefik.http.routers.immich-http.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.immich-http.middlewares=immich-https"

      - 'com.centurylinklabs.watchtower.enable=true'

    networks:
      - default
      - traefik_network

    depends_on:
      - server
      - web


networks:
  traefik_network:
    external: true
